#!/usr/bin/env python

# Run this before you deploy it on replicate
import os
import sys
import torch
from diffusers import AutoPipelineForInpainting

# append project directory to path so predict.py can be imported
sys.path.append('.')
from predict import MODEL_NAME, MODEL_CACHE

# Make cache folders
if not os.path.exists(MODEL_CACHE):
    os.makedirs(MODEL_CACHE)

pipe = AutoPipelineForInpainting.from_pretrained(
    MODEL_NAME,
    torch_dtype=torch.float16,
    variant="fp16"
)
pipe.save_pretrained(MODEL_CACHE, safe_serialization=True)
